services:
  caddy:
    image: caddy:2.11.2-alpine@sha256:834468128c7696cec0ceea6172f7d692daf645ae51983ca76e39da54a97c570d
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      # - 443:443
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  caddy_data:
  caddy_config:
