services:
  jellyfin:
    image: jellyfin/jellyfin:2026042706@sha256:5aa5c9b240eff60481e8ea1f9b3140649d01cd0295f9506b698adbc524279b80
    container_name: jellyfin
    user: 1000:988
    group_add:
      - '992' # Result of: getent group render | cut -d: -f3
    volumes:
      - /srv/appdata/jellyfin/config:/config
      - /srv/appdata/jellyfin/cache:/cache
      - type: bind
        source: /mnt/data/media
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
    network_mode: "service:gluetun"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    user: 1000:1000
    environment:
      - TZ=Europe/Paris
    volumes:
      - /srv/appdata/prowlarr:/config
    restart: unless-stopped
    network_mode: "service:gluetun"
  seerr:
    image: ghcr.io/seerr-team/seerr:sha-b32ab02@sha256:4410e9a18f889aedfae82b45625ad1f77b8504a09ca74ef28a8ee64313f219cd
    init: true
    container_name: seerr
    security_opt:
      - no-new-privileges:true
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
      - PORT=5055 #optional
    volumes:
      - /srv/appdata/seer/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    network_mode: "service:gluetun"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    user: 1000:1000
    environment:
      - TZ=Europe/Paris
    volumes:
      - /srv/appdata/radarr/config:/config
      - /home/bertrand/data/torrents:/torrents
      - /mnt/data/media:/media
    restart: unless-stopped
    network_mode: "service:gluetun"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    user: 1000:1000
    environment:
      - TZ=Europe/Paris
    volumes:
      - /srv/appdata/sonarr/config:/config
      - /home/bertrand/data/torrents:/torrents
      - /mnt/data/media:/media
    restart: unless-stopped
    network_mode: "service:gluetun"
  sportarr:
    image: sportarr/sportarr:latest
    container_name: sportarr
    user: 1000:1000
    environment:
      - UMASK=022
      - TZ=Europe/Paris
    volumes:
      - /srv/appdata/sportarr:/config
      - /home/bertrand/data/torrents:/torrents
      - /mnt/data/media:/media
    restart: unless-stopped
    network_mode: "service:gluetun"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4@sha256:3679a75dd2304b695525d83a4ff14c458708b5da4a7ce53044240932139590e1
    container_name: qbittorrent
    user: 1000:1000
    environment:
      - TZ=Europe/Paris
      - WEBUI_PORT=9092
      - TORRENTING_PORT=${FORWARDED_PORT}
    volumes:
      - /srv/appdata/qbittorrent:/config
      - /home/bertrand/data/torrents:/torrents
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "service:gluetun"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    user: 1000:1000
    environment:
      - LOG_LEVEL=info
      - LOG_FILE=none
      - LOG_HTML=false
      # - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    volumes:
      - /srv/appdata/flaresolverr:/config
    restart: unless-stopped
    network_mode: "service:gluetun"
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /srv/appdata/bazarr:/config
      - /mnt/data/media:/media
    restart: unless-stopped
    network_mode: "service:gluetun"
  gluetun:
    image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      - 9696:9696 # Prowlarr
      - 5055:5055 # Seer
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 1867:1867 # Sportarr
      - 9092:9092 # qBittorrent
      - 8096:8096/tcp # Jellyfin
      - 7359:7359/udp # Jellyfin
      - 6767:6767 # Bazarr
    environment:
      - TZ=Europe/Paris
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=Netherlands,Switzerland
      - FIREWALL_VPN_INPUT_PORTS=${FORWARDED_PORT}
      - UPDATER_PERIOD=24h
      - DNS_UPSTREAM_RESOLVERS=quad9 secured,libredns
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
    volumes:
      - /srv/appdata/gluetun:/gluetun
    env_file:
      - .env
    restart: unless-stopped
