name: adguardhome

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.74@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 8080:80/tcp # http web interface
      # - 3000:3000/tcp # initial setup web interface
    volumes:
      - config:/opt/adguardhome/conf # app configuration
      - work:/opt/adguardhome/work # app working directory
    restart: unless-stopped
    healthcheck:
      test: "/bin/netstat -pant | /bin/grep ':::53' || exit 1"
      interval: 120s
      timeout: 30s
      retries: 3

volumes:
  config:
    driver: local
  work:
    driver: local
