services:
  openvpn-as:
    image: openvpn/openvpn-as:3.1.0-e22fe316-Ubuntu24@sha256:588f5288e1cf1d31bb5a7419fda7bd6774fcb39fdc21ff40827afbaaf1aded35
    container_name: openvpn-as
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - MKNOD
    ports:
      - 943:943
      - 443:443
      - 1194:1194/udp
    volumes:
      - /srv/appdata/openvpn:/openvpn
    restart: unless-stopped
