services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - '/home/bertrand/downloads/:/data'
      - '/home/bertrand/transmission-data/:/config'
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - NORDVPN_COUNTRY=NL
      - NORDVPN_CATEGORY=p2p
      - NORDVPN_PROTOCOL=tcp
      - LOCAL_NETWORK=192.168.0.0/16
      # Fix random crashes
      # https://github.com/haugene/docker-transmission-openvpn/discussions/2064#discussioncomment-3021938
      - CONFIG_MOD_PING=0
      - OPENVPN_OPTS=--ping 10 --pull-filter ignore ping
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9092:9091'
    image: haugene/transmission-openvpn
    env_file:
      - .env
